export const Characters = {
	ALPHA: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
	ALPHA_WITHSPACE: "ABCDEFGHIJKLMNOPQRSTUVWXYZ ",
	ALPHANUMERIC: "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789",
	ALPHANUMERIC_WITHSPACE: "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 ",
};
